### ISSUE TITLE
Chest replaced with stone when backpack landed on it

### ISSUE THREAD

**Issue by itanshi** [copygirl/BetterStorage#258]
I'm not confident which mod led to this, but this occurred on phoenix craft 2.1.01. I'm not sure which version of better storage it runs.

Upon sleeping via witchery the backpack drops. It landed on an electric chest from Mekanism. it did not recognize the chest as a block and replaced what it thought as air with stone.

http://imgur.com/tlfSQf0

**Comment by copygirl** [comment]
Closing this for now since I didn't get a response.
