### ISSUE TITLE
BetterStorage conflicting with various mods (java.lang.AssertionError)

### ISSUE THREAD

**Issue by Yulife** [copygirl/BetterStorage#268]
Forge 1240
Latest BetterStorage
Latest Quadrum

A crash occurs whenever I try to launch an instance with both Quadrum and BetterStorage.
[Log here](http://paste.ee/p/ixtfU)

**Comment by disconsented** [comment]
I have had a user report what appears to be the same issue to me(or something similar), however it is between my mod and better storage (DEV8 and B123 respective) http://pastebin.com/jcS0RW6C

**Comment by BigXplosion** [comment]
we have looked into this again and Quadrum is only crashing with this mod and still has the same error as reported above. I would like to find out what the issue is as a lot of people are using better storage together with quadrum

**Comment by copygirl** [comment]
@BigXplosion Looking around a bit... it *might* have to do with enums being serialized to JSON (using gson)..? If the enums have been modified, looks like it crashes with that error. [Here for example](https://github.com/copygirl/BetterStorage/blob/master/src/main/java/net/mcft/copy/betterstorage/item/cardboard/ItemCardboardSheet.java#L16) I add new tool and armor materials. What types are you saving? Sorry if this this isn't it. It's just a stab in the dark anyway.

**Comment by BigXplosion** [comment]
@copygirl, I don't think this is the error we are looking for, the reported errors have only been reported with errors in the block loading. Second thing is that we never serialize enums, the only place we use enums for our [TypeSpecific annotation](https://github.com/BigXplosion/Quadrum-2/blob/master/src/main/java/quadrum/lib/TypeSpecific.java) used in the [data](https://github.com/BigXplosion/Quadrum-2/blob/master/src/main/java/quadrum/block/data/BlockData.java#L49) that is read from the json to determine if the given option is valid for the type of block users try to create. I've been looking extensively in your and our code but haven't found anything that might cause this :/

**Comment by copygirl** [comment]
Tried setting up Quadrum in my dev workspace so I could step through and look where it's hanging, but I'm not able to get NEI/CCC/CCL to work. Sorry. Can you have a go?

**Comment by BigXplosion** [comment]
The normal setup doesn't require NEI/CCC/CCL and those have always been tricky for me to setup. but if you really want, the thing I have to do is add them as dependencies in gradle (via maven) and ALSO put them in the mods folder. You will also have to add the mods from the mods folder to your module dependencies in the project structure in intellij (if you use intellij).

**Comment by copygirl** [comment]
NEI requirement is actually on my side. I've not touched any MC code recently, so... that's that.
Can't reproduce the crash in my dev environment, do I need some items set up?

**Comment by BigXplosion** [comment]
The crash doesn't happen yet as no json/gson file is being read, you'll need a basic block JSON file [like this] (http://pastebin.com/Vnfg0jAG) in the config/Quadrum/block folder (should be auto generated).

**Comment by copygirl** [comment]
It's EnumEnchantmentType that's breaking, apparently? BetterStorage adds its own lock and key enchantment types. Can you do anything with that?

**Comment by BigXplosion** [comment]
Sadly no, I have no clue why that would break it, as I don't check for anything related to Enchantments... But I'll look into it tomorrow. Also how did you figure this out?

**Comment by copygirl** [comment]
I set a breakpoint of one of the related functions and checked the type variable.

**Comment by Yulife** [comment]
Quadrum is discontinued,  can be closed I guess :)
