### ISSUE TITLE
Internal server error with Backpack and TE's Autonomous Activators

### ISSUE THREAD

**Issue by Glomzubuk** [copygirl/BetterStorage#279]
So, i found myself getting Internal Server Error when playing near TE's Autonomous activators with a backpack equipped.
Here is the server log:
http://pastebin.com/dqSv6NLd

It only happens if i show them my back so i believe it's because they try to access it like a normal player.

Tell me if i need to report it on the TE's repo too.

**Comment by copygirl** [comment]
Definitely something I'll fix.

May also a good idea if TE catches exceptions like this (if possible) since it's basically able to interact with anything. Though, if it didn't crash, I wouldn't have heard about the issue. So it's a double-edged sword.

**Comment by Glomzubuk** [comment]
I'll disable the option to access the backpack when it is equipped for now then.
Great mod BTW, I love it and my friends do too =P

**Comment by copygirl** [comment]
Does this test build fix it?
https://docs.google.com/file/d/0ByaJlPeqIEMhNjdTMlZNWE5kUEU

**Comment by Glomzubuk** [comment]
I need a permission to access your file.

**Comment by Glomzubuk** [comment]
I believe it's fixed, however, i could only test it in a single player environment.
I'll try it on my server tomorrow.

**Comment by copygirl** [comment]
Did you check it on the server? Is it fixed?

**Comment by Glomzubuk** [comment]
Sorry, i hadn't the opportunity to play the last few days.
No, it isn't fixed, the bug still happens when i turn my back to an autonomous.
