### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Speiger** [copygirl/BetterStorage#283]
Hello copygirl.
I am a fan of your Better Storage Locking system (and some other stuff too),
and i want to ask if i am allowed to use some of your code (coping it) for the mod i am Porting.
I was thinking of adding Lock Support for the IC2 (Classic Version) Reinforced door.
Maybe even some more blocks if i find some.

Speiger

**Comment by copygirl** [comment]
As I always say, my mods are all officially licensed under MIT and unofficially public domain. So yes.

**Comment by Speiger** [comment]
ok thanks,
i did not really find a permission file of any kind. So asking did help xD

**Comment by copygirl** [comment]
In case you have further questions, there's other ways to contact me :)
