### ISSUE TITLE
BetterStorage compatibility issue with the newest Armourer's Workshop

### ISSUE THREAD

**Issue by abidoang** [copygirl/BetterStorage#286]
It seemed that BetterStorage (0.12.0.124) isn't compatible with the newest version of Armourer's Workshop ver. 0.31.2.82
Crash log: http://pastebin.com/NpmTvSAy

The Armourer's Workshop author approved that it was caused by BetterStorage. More details on the author's post : http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/wip-mods/2309193-wip-alpha-armourers-workshop-weapon-armour-skins?comment=343

**Comment by copygirl** [comment]
RiskyKen actually already submitted a PR. I just haven't built a version with it yet. And not sure when I will ... ^^"
