### ISSUE TITLE
Crash when placing Cobblestone in the Crafting Station

### ISSUE THREAD

**Issue by Vazkii** [copygirl/BetterStorage#292]
http://paste.ee/p/UeFmY
Apologies for the invalid log, but that's what I got :V

**Comment by copygirl** [comment]
It *may* be due to a recipe matching the crafting input, but returning null for the crafting result. Would you be so kind to test by removing mods until there's (hopefully only) one remaining that causes the crash?

**Comment by copygirl** [comment]
Closing for now because lack of response.
