### ISSUE TITLE
Can't pull from crafting station

### ISSUE THREAD

**Issue by Shukaro** [copygirl/BetterStorage#297]
This is in blightfall, in case it's some sort of mod interaction
B:enableStationAutoCrafting=true is set

Tried with both hoppers and item translocators attached to the bottom, with the station properly configured and stocked.

**Comment by copygirl** [comment]
I was about to write something up and ... I totally forgot in the newest version, the crafting station needs a redstone signal to craft. Reason for that is proper auto-crafting support, which was not possible with how it worked previously - only "crafting" once the items were already taken out, at which point it wouldn't be possible to modify them anymore (which some features requires, specifically proper MineTweaker support).

**Comment by Shukaro** [comment]
Yep, it's working as expected now when there's a redstone signal.
