### ISSUE TITLE
Reinforced chests blow up

### ISSUE THREAD

**Issue by Ganjalf-Amsterdoom** [copygirl/BetterStorage#311]
Hello,

aren't reinforced chests supposed to not blow up? I placed a tnt on top of reinforced iron chest and kaboom, chest broken and content spread around.

Thank you for your time.

**Comment by copygirl** [comment]
They're only 100% creeper-proof. TNT just barely blows them up when placed right next to them. Locks with persistence enchantment improve their blast resistance. Unsure if locks on their own do anything.

**Comment by Ganjalf-Amsterdoom** [comment]
Thank you I just realized that and did some testing, I was more concerned for charged creepers wich will blow up reinforced chest and lockers even with enchanted lock.
