### ISSUE TITLE
PneumaticCraft helm crashes client when searching a Crate

### ISSUE THREAD

**Issue by belathus** [copygirl/BetterStorage#315]
http://pastebin.com/qbWjmMwu

**Comment by copygirl** [comment]
Thanks for also reporting it to the PneumaticCraft tacker!
MineMaarten/PneumaticCraft#809
I will respond there.

**Comment by belathus** [comment]
Thank you for replying there, copygirl. I try to report issues to both trackers when I find a crossmod crash, so you're welcome on that front.
