### ISSUE TITLE
Publicly readable feature list?

### ISSUE THREAD

**Issue by relsqui** [copygirl/BetterStorage#327]
I don't want to give my personal information to two different third-party companies (the forum website and one of its two unsavory login providers) just to find out what's even in this mod. I hope you'll consider putting at least a minimal feature overview somewhere that everyone can read it.

**Comment by copygirl** [comment]
I did not switch to Twitch and that probably deleted all of my content on the forums. Not sure why it wants you to log in when ít's likely dead, anyway. You can check out [this archived version](https://web.archive.org/web/20180105152040/http://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/wip-mods/1442380-betterstorage-0-13-1-127-wip) of the thread, though. Some features are also detailed on the [FTB Wiki page](https://ftb.gamepedia.com/BetterStorage) on it.

**Comment by relsqui** [comment]
Oh nice, that helps. Thank you!
